version: '3.8'

services:
   web:
      container_name: COPLAIM_BACKEND
      restart: always
      build: .
      ports:
         - ${PORT_TCP}:${APP_PORT}
      environment:
         HANA_DB_COPLAIM: ${HANA_DB_COPLAIM}
         HANA_DB_DATOS: ${HANA_DB_DATOS}
         HANA_DB_EMVCLI: ${HANA_DB_EMVCLI}
         HANA_DB_SGEP: ${HANA_DB_SGEP}
         HANA_DB_CHERNO: ${HANA_DB_CHERNO}
         HANA_HOST: ${HANA_HOST}
         HANA_PORT: ${HANA_PORT}
         HANA_USERNAME: ${HANA_USERNAME}
         HANA_PASSWORD: ${HANA_PASSWORD}
         HANA_DATABASE: ${HANA_DATABASE}
         HANA_DATABASE_AU: ${HANA_DATABASE_AU}
         OFFICE_HOST: ${OFFICE_HOST}
         OFFICE_PORT: ${OFFICE_PORT}
         OFFICE_USER: ${OFFICE_USER}
         OFFICE_PASS: ${OFFICE_PASS}
         SECRET_SESSION: ${SECRET_SESSION}
         AD_URL: ${AD_URL}
         AD_BASEDN: ${AD_BASEDN}
         APP_PORT: ${APP_PORT}
         API_NODE_RED: ${API_NODE_RED}
         SECRET_TOKEN: ${SECRET_TOKEN}
         CLIENT_SERVER: ${CLIENT_SERVER}
         COOKIE_HTTP: ${COOKIE_HTTP}
         COOKIE_SECURE: ${COOKIE_SECURE}
         COOKIE_MAXAGE: ${COOKIE_MAXAGE}
         COOKIE_SAMESITE: ${COOKIE_SAMESITE}
         EMAIL_BODEGA: ${EMAIL_BODEGA}
         NAME_BODEGA: ${NAME_BODEGA}
         API_JOBS: ${API_JOBS}
         EMAIL_GERENCIA: ${EMAIL_GERENCIA}
         EMAIL_CONTABILIDAD: ${EMAIL_CONTABILIDAD}
         PASS_CONTABILIDAD: ${PASS_CONTABILIDAD}
         EMAIL_IMPORTACIONES: ${EMAIL_IMPORTACIONES}
         PASS_IMPORTACIONES: ${PASS_IMPORTACIONES}
         EMAIL_ACCOUNTS: ${EMAIL_ACCOUNTS}
         SL_URL: ${SL_URL}
         SL_USER: ${SL_USER}
         SL_PASS: ${SL_PASS}
         AUTH_PRIV_ACCT: ${AUTH_PRIV_ACCT}
         AUTH_USER_ACCT: ${AUTH_USER_ACCT}
         AUTH_MAIL_ACCT: ${AUTH_MAIL_ACCT}
         EMAIL_IMP: ${EMAIL_IMP}
         API_BACKEND: ${API_BACKEND}
         AUTH_COTI_ID: ${AUTH_COTI_ID}
         AUTH_COTI_PRIV: ${AUTH_COTI_PRIV}
         PROCENTAJE_MERMA: ${PROCENTAJE_MERMA}
         EMAIL_CONTRALOR: ${EMAIL_CONTRALOR}
         PASS_CONTRALOR: ${PASS_CONTRALOR}
         NAME_CONTRALOR: ${NAME_CONTRALOR}
         TEL_CONTRALOR: ${TEL_CONTRALOR}
         EMAIL_COMUNICATION: ${EMAIL_COMUNICATION}
         EMAIL_CONTABILIDAD_AU: ${EMAIL_CONTABILIDAD_AU}
         PASS_CONTABILIDAD_AU: ${PASS_CONTABILIDAD_AU}
         SAP_ENCRYPTION_KEY: ${SAP_ENCRYPTION_KEY}
         REDIS_URL: ${REDIS_URL}
         JWT_SECRET_CREATED: ${JWT_SECRET_CREATED}
         JWT_SECRET_ROTATION_DAYS: ${JWT_SECRET_ROTATION_DAYS}
         NODE_ENV: ${NODE_ENV}
      volumes:
         - ${SYNC_DOCS}BACKEND_CORRU:/usr/src/BACKEND_CORRU/src/docs   # VOL_PC:VOL_DOCKER
