/** ESQUEMA DE LOS PUERTOS **/
CREATE COLUMN TABLE GC_COPLAIM."PRTO" (
	"ID_PRTO" NVARCHAR(50) CS_STRING PRIMARY KEY,
	"ID_CANT" NVARCHAR(100) CS_STRING NOT NULL,
	"NOMBRE" NVARCHAR(100) CS_STRING NOT NULL,
	"DIRECCION" NVARCHAR(100) CS_STRING NOT NULL,
	"EMAIL" NVARCHAR(100) CS_STRING NOT NULL,
	"DUENIO" NVARCHAR(100) CS_STRING NOT NULL,
	"TELEFONO_ONE" NVARCHAR(50) CS_STRING NOT NULL,
	"TELEFONO_TWO" NVARCHAR(50) CS_STRING NOT NULL,
	"USER" NVARCHAR(50) CS_STRING NOT NULL,
	"CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "GC_COPLAIM"."PRTO" ADD CONSTRAINT "PRTO_FK_ID_CANT" FOREIGN KEY ("ID_CANT") REFERENCES "GC_COPLAIM"."CCANT" ("ID_CANT")
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;

/** ESQUEMA DE TIPO DE IMPORTACION **/
CREATE COLUMN TABLE GC_COPLAIM."TIMPT" (
	"ID_TIMPT" NVARCHAR(50) CS_STRING PRIMARY KEY,
	"TIPO_IMPORT" NVARCHAR(100) CS_STRING NOT NULL,
	"USER" NVARCHAR(50) CS_STRING NOT NULL,
	"CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

/** ESQUEMA PRINCIPAL DE LA IMPORTACION DE PAPEL **/
CREATE COLUMN TABLE GC_COPLAIM."IMPT" (
	"ID_IMPT" NVARCHAR(50) CS_STRING PRIMARY KEY,
	"ID_PAIS" NVARCHAR(100) CS_STRING NOT NULL,
	"ID_PRTO" NVARCHAR(50) CS_STRING NOT NULL,
	"ID_TIMPT" NVARCHAR(50) CS_STRING NOT NULL,
	"ID_FIMPORTA" NVARCHAR(50) CS_STRING NOT NULL,
	"ORDEN_COMPRA" INTEGER CS_INT DEFAULT 0,
	"FACTURA" NVARCHAR(50) CS_STRING,
	"DAI" NVARCHAR(50) CS_STRING NOT NULL,
	"MRN" NVARCHAR(50) CS_STRING NOT NULL,
	"BL" NVARCHAR(50) CS_STRING NOT NULL,
	"PROVEEDOR" NVARCHAR(50) CS_STRING NOT NULL,
	"DATE_ARRIBO" LONGDATE CS_LONGDATE NOT NULL,
	"VENC_ECAS" LONGDATE CS_LONGDATE NOT NULL,
	"REGIMEN" INTEGER CS_INT DEFAULT 21, --10 / 21
	"COMENTARIO" NVARCHAR(1000) CS_STRING,
	"USER" NVARCHAR(50) CS_STRING NOT NULL,
	"CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "GC_COPLAIM"."IMPT" ADD CONSTRAINT "IMPT_FK_ID_PAIS" FOREIGN KEY ("ID_PAIS") REFERENCES "GC_COPLAIM"."CPAIS" ("ID_PAIS")
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;

ALTER TABLE "GC_COPLAIM"."IMPT" ADD CONSTRAINT "IMPT_FK_ID_PRTO" FOREIGN KEY ("ID_PRTO") REFERENCES "GC_COPLAIM"."PRTO" ("ID_PRTO")
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;

ALTER TABLE "GC_COPLAIM"."IMPT" ADD CONSTRAINT "IMPT_FK_ID_TIMPT" FOREIGN KEY ("ID_TIMPT") REFERENCES "GC_COPLAIM"."TIMPT" ("ID_TIMPT")
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;

/** ESQUEMA DE LOS CONTENEDORES **/
CREATE COLUMN TABLE GC_COPLAIM."CNTNR" (
	"ID_CNTNR" NVARCHAR(50) CS_STRING PRIMARY KEY,
	"ID_IMPT" NVARCHAR(50) CS_STRING NOT NULL,
	"COD_CONTENEDOR" NVARCHAR(50) CS_STRING NOT NULL,
	"DATE_LLEGADA" LONGDATE CS_LONGDATE NOT NULL,
	"DEVOLUCION" NVARCHAR(10) CS_STRING DEFAULT 'N',
	"DEV_DESTINO" NVARCHAR(50) CS_STRING NOT NULL,
	"VENC_ECAS" LONGDATE CS_LONGDATE NOT NULL,
	"PESO" DOUBLE CS_DOUBLE DEFAULT 0,
	"COMENTARIO" NVARCHAR(1000) CS_STRING,
	"USER" NVARCHAR(50) CS_STRING NOT NULL,
	"CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "GC_COPLAIM"."CNTNR" ADD CONSTRAINT "CNTNR_FK_ID_IMPT" FOREIGN KEY ("ID_IMPT") REFERENCES "GC_COPLAIM"."IMPT" ("ID_IMPT")
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;

/** ESQUEMA DE TIPO DE FACTURAS **/
CREATE COLUMN TABLE GC_COPLAIM."TINVC" (
	"ID_TINVC" NVARCHAR(50) CS_STRING PRIMARY KEY,
	"TIPO" NVARCHAR(100) CS_STRING NOT NULL,
	"USER" NVARCHAR(50) CS_STRING NOT NULL,
	"CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

/** ESQUEMA DE TIPO DE FACTURAS **/
CREATE COLUMN TABLE GC_COPLAIM."INVC" (
	"ID_INVC" NVARCHAR(50) CS_STRING PRIMARY KEY,
	"ID_TINVC" NVARCHAR(50) CS_STRING NOT NULL,
	"ID_IMPT" NVARCHAR(50) CS_STRING NOT NULL,
	"COMENTARIO" NVARCHAR(1000) CS_STRING,
	"USER" NVARCHAR(50) CS_STRING NOT NULL,
	"CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "GC_COPLAIM"."INVC" ADD CONSTRAINT "INVC_FK_ID_TINVC" FOREIGN KEY ("ID_TINVC") REFERENCES "GC_COPLAIM"."TINVC" ("ID_TINVC")
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;

ALTER TABLE "GC_COPLAIM"."INVC" ADD CONSTRAINT "INVC_FK_ID_IMPT" FOREIGN KEY ("ID_IMPT") REFERENCES "GC_COPLAIM"."IMPT" ("ID_IMPT")
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;

/** ESQUEMA DE LOS INSUMOS **/
CREATE COLUMN TABLE GC_COPLAIM."INSM" (
	"ID_INSM" NVARCHAR(50) CS_STRING PRIMARY KEY,
	"ID_INVC" NVARCHAR(50) CS_STRING NOT NULL,
	"DETALLE" NVARCHAR(100) CS_STRING NOT NULL,
	"CANTIDAD" INTEGER CS_INT DEFAULT 0,
	"USER" NVARCHAR(50) CS_STRING NOT NULL,
	"CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "GC_COPLAIM"."INSM" ADD CONSTRAINT "INSM_FK_ID_INVC" FOREIGN KEY ("ID_INVC") REFERENCES "GC_COPLAIM"."INVC" ("ID_INVC")
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;

/** ESQUEMA DE LOS TIPOS DE PAPEL **/
CREATE COLUMN TABLE GC_COPLAIM."TPAP" (
	"ID_TPAP" NVARCHAR(50) CS_STRING PRIMARY KEY,
	"COD_PAPEL" NVARCHAR(50) CS_STRING NOT NULL,
	"DETALLE" NVARCHAR(100) CS_STRING NOT NULL,
	"USER" NVARCHAR(50) CS_STRING NOT NULL,
	"CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

/** ESQUEMA DE LOS PAPELES O BOBINAS **/
CREATE COLUMN TABLE GC_COPLAIM."BOBI" (
	"ID_BOBI" NVARCHAR(50) CS_STRING PRIMARY KEY,
	"ID_TPAP" NVARCHAR(50) CS_STRING NOT NULL,
	"ID_CNTNR" NVARCHAR(50) CS_STRING NOT NULL,
	"ID_INVC" NVARCHAR(50) CS_STRING NOT NULL,
	"ID_PAPEL" NVARCHAR(50) CS_STRING NOT NULL,
	"CODIGO" NVARCHAR(50) CS_STRING NOT NULL,
	"LOTE" NVARCHAR(50) CS_STRING NOT NULL,
	"ANCHO" DOUBLE CS_DOUBLE DEFAULT 0,
	"LARGO" DOUBLE CS_DOUBLE DEFAULT 0,
	"GRAMAJE" DOUBLE CS_DOUBLE DEFAULT 0,
	"PESO" DOUBLE CS_DOUBLE DEFAULT 0,
	"MLINEALES" DOUBLE CS_DOUBLE DEFAULT 0,
	"CANTIDAD" INTEGER CS_INT DEFAULT 0,
	"ESTADO" NVARCHAR(50) CS_STRING DEFAULT 'A',
	"COMENTARIO" NVARCHAR(1000) CS_STRING,
	"USER" NVARCHAR(50) CS_STRING NOT NULL,
	"CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "GC_COPLAIM"."BOBI" ADD CONSTRAINT "BOBI_FK_ID_TPAP" FOREIGN KEY ("ID_TPAP") REFERENCES "GC_COPLAIM"."TPAP" ("ID_TPAP")
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;

ALTER TABLE "GC_COPLAIM"."BOBI" ADD CONSTRAINT "BOBI_FK_ID_CNTNR" FOREIGN KEY ("ID_CNTNR") REFERENCES "GC_COPLAIM"."CNTNR" ("ID_CNTNR")
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;

ALTER TABLE "GC_COPLAIM"."BOBI" ADD CONSTRAINT "BOBI_FK_ID_INVC" FOREIGN KEY ("ID_INVC") REFERENCES "GC_COPLAIM"."INVC" ("ID_INVC")
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;

/* ESQUEMA DE LOS LOGS DE CORREOS - FR21 */
CREATE COLUMN TABLE "GC_COPLAIM"."LOGS" (
   "ID_LOGS" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
   "CODE" NVARCHAR(100) NOT NULL,
   "MOTIVO" NVARCHAR(100),
   "USER" NVARCHAR(50) NOT NULL,
   "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

/* ESQUEMA DE LAS ORDEN DE COMPRAS - ORDC */
CREATE COLUMN TABLE "GC_COPLAIM"."ORDC" (
   "ID_ORDC" INTEGER CS_INT GENERATED BY DEFAULT AS IDENTITY,
   "DocEntry" INTEGER CS_INT NOT NULL,
   "DocNum" INTEGER CS_INT NOT NULL,
   "USER" NVARCHAR(50) NOT NULL,
   "ESTADO" NVARCHAR(50) CS_STRING DEFAULT 'R',
   "TIPO_DOC" INTEGER CS_INT DEFAULT 30,
   "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);