CREATE COLUMN TABLE "GC_COPLAIM"."CPAIS" (
	"ID_PAIS" NVARCHAR(100) CS_STRING PRIMARY KEY,
	"COD_PAIS" NVARCHAR(100) CS_STRING NOT NULL,
	"PAIS" NVARCHAR(100) CS_STRING NOT NULL,
	"CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE COLUMN TABLE "GC_COPLAIM"."CPROV" (
	"ID_PROV" NVARCHAR(100) CS_STRING PRIMARY KEY,
	"ID_PAIS" NVARCHAR(100) CS_STRING NOT NULL,
	"PROVINCIA" NVARCHAR(100) CS_STRING NOT NULL,
	"CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "GC_COPLAIM"."CPROV" ADD CONSTRAINT "CPROV_FK_ID_CPAIS" FOREIGN KEY ("ID_PAIS") REFERENCES "GC_COPLAIM"."CPAIS" ("ID_PAIS")
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;

CREATE COLUMN TABLE "GC_COPLAIM"."CCANT" (
	"ID_CANT" NVARCHAR(100) CS_STRING PRIMARY KEY,
	"ID_PROV" NVARCHAR(100) CS_STRING NOT NULL,
	"CANTON" NVARCHAR(100) CS_STRING NOT NULL,
	"KILOMETROS" INTEGER CS_INT,
	"PEAJES" INTEGER CS_INT DEFAULT 0,
	"CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "GC_COPLAIM"."CCANT" ADD CONSTRAINT "CCANT_FK_ID_CPROV" FOREIGN KEY ("ID_PROV") REFERENCES "GC_COPLAIM"."CPROV" ("ID_PROV")
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;